### ISSUE TITLE
Crashing Intermittently

### ISSUE THREAD

**Issue by nythe** [WreckedAvent/slimCat#347]
I'm not entirely sure what's causing the crash, but every once in a while it simply freezes up and errors out with the following stacktrace:

Version: slimCat Puma 4.11
Exception: Insufficient memory to continue the execution of the program.
Occured at: PresentationCore

Immediate stack trace: Void SyncFlush()   at System.Windows.Media.Composition.DUCE.Channel.SyncFlush()
   at System.Windows.Interop.HwndTarget.UpdateWindowSettings(Boolean enableRenderTarget, Nullable`1 channelSet)
   at System.Windows.Interop.HwndTarget.UpdateWindowSettings(Boolean enableRenderTarget)
   at System.Windows.Interop.HwndTarget.HandleMessage(WindowMessage msg, IntPtr wparam, IntPtr lparam)
   at System.Windows.Interop.HwndSource.HwndTargetFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by WreckedAvent** [comment]
> Insufficient memory to continue the execution of the program

Seems like you have the problem right there?

**Comment by nythe** [comment]
It's not any issue with my computer - I've got SlimCat using up maybe 100 megs of RAM, and I have 8 gigs free.

**Comment by WreckedAvent** [comment]
Is there any particular things which cause it to crash them? Looking at a profile with a very large image, perhaps?

**Comment by nythe** [comment]
Nothing that I can see. I’ll just be browsing the internet with slimCat open on my other monitor when it crashes.

**Comment by nythe** [comment]
An update - I just had it happen to me again. This time, it happened when bringing a window into focus that had been active for a couple of hours.

**Comment by nythe** [comment]
Another update - it seems that there is something causing the used memory of slimCat to balloon - on the latest crash it was using up over 1.5 gigs of memory.

**Comment by WreckedAvent** [comment]
How long do you have slimCat open before it crashes?

**Comment by nythe** [comment]
It varies, but usually several hours

**Comment by nythe** [comment]
Just an update - after playing around with things, it seems to be tied to toast notifications - with them disabled, I no longer get this crash.

**Comment by WreckedAvent** [comment]
That is weird. Usually when I hear people complain about this `out of memory` issue it comes from copy/pasting things. Hmm.
