### ISSUE TITLE
Exception error

### ISSUE THREAD

**Issue by Cleverbird** [WreckedAvent/slimCat#373]
Been getting this error from time to time when opening a PM with someone:

====================================
BEGIN EXCEPTION REPORT
22-6-2015 8:49:05
====================================

Version: slimCat Puma 4.11
Exception: Index was outside the bounds of the array.
Occured at: PM Channel ViewModel, init

Immediate stack trace: Boolean MoveNext()   at System.Collections.Generic.List`1.Enumerator.MoveNext()
   at System.Linq.Enumerable.WhereListIterator`1.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Microsoft.Practices.Unity.NamedTypesRegistry.RegisterType(Type t, String name)
   at Microsoft.Practices.Unity.UnityDefaultBehaviorExtension.OnRegister(Object sender, RegisterEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at Microsoft.Practices.Unity.UnityContainer.RegisterType(Type from, Type to, String name, LifetimeManager lifetimeManager, InjectionMember[] injectionMembers)
   at Microsoft.Practices.Unity.UnityContainerExtensions.RegisterType[TFrom,TTo](IUnityContainer container, String name, InjectionMember[] injectionMembers)
   at slimCat.ViewModels.PmChannelViewModel..ctor(String name, IChatState chatState, INoteService notes, IProfileService profile) in c:\Users\Justin\Source\Repos\slimCat\slimCat\ViewModels\Channels\PMChannelViewModel.cs:line 110

====================================
END EXCEPTION REPORT
====================================

No idea what's causing it, but my Stacktrace.log is riddled with them

**Comment by WreckedAvent** [comment]
Was not able to reproduce myself, but it appears to be related to the way slimCat registers new PM tabs. Not sure if this is resolve-able.

**Comment by Cleverbird** [comment]
That is a shame to hear, but the error doesnt pop up all that often so its not the end of the world.
