### ISSUE TITLE
MILERR_WIN32ERROR

### ISSUE THREAD

**Issue by WreckedAvent** [WreckedAvent/slimCat#407]
Example:
```
====================================
BEGIN EXCEPTION REPORT
2016-08-23 4:59:18 AM
====================================
 
Version: slimCat Slow Cheetah 5.01 dev
Exception: MILERR_WIN32ERROR (Exception from HRESULT: 0x88980003)
Occured at: PresentationCore
 
Immediate stack trace: Void CopyCommon(System.Windows.Media.Imaging.RenderTargetBitmap)   at System.Windows.Media.Imaging.RenderTargetBitmap.CopyCommon(RenderTargetBitmap sourceBitmap)
   at System.Windows.Media.Imaging.RenderTargetBitmap.CloneCurrentValueCore(Freezable sourceFreezable)
   at System.Windows.Freezable.CloneCoreCommon(Freezable sourceFreezable, Boolean useCurrentValue, Boolean cloneFrozenValues)
   at System.Windows.Freezable.CloneCurrentValueCore(Freezable sourceFreezable)
   at System.Windows.Freezable.CloneCurrentValue()
   at System.Windows.Media.Animation.ObjectKeyFrameCollection.CloneCurrentValueCore(Freezable sourceFreezable)
   at System.Windows.Freezable.CloneCurrentValue()
   at System.Windows.Media.Animation.ObjectAnimationUsingKeyFrames.CopyCommon(ObjectAnimationUsingKeyFrames sourceAnimation, Boolean isCurrentValueClone)
   at System.Windows.Media.Animation.ObjectAnimationUsingKeyFrames.GetCurrentValueAsFrozenCore(Freezable source)
   at System.Windows.Freezable.GetCurrentValueAsFrozen()
   at System.Windows.Media.Animation.Clock..ctor(Timeline timeline)
   at System.Windows.Media.Animation.AnimationTimeline.AllocateClock()
   at System.Windows.Media.Animation.Clock.AllocateClock(Timeline timeline, Boolean hasControllableRoot)
   at System.Windows.Media.Animation.Clock.BuildClockTreeFromTimeline(Timeline rootTimeline, Boolean hasControllableRoot)
   at WpfAnimatedGif.ImageAnimationController..ctor(Image image, ObjectAnimationUsingKeyFrames animation, Boolean autoStart)
   at WpfAnimatedGif.ImageBehavior.InitAnimationOrImage(Image imageControl)
   at WpfAnimatedGif.ImageBehavior.<>c__DisplayClass30_1.<InitAnimationOrImage>b__0(Object sender, EventArgs args)
   at System.Windows.Media.UniqueEventHelper.InvokeEvents(Object sender, EventArgs args)
   at System.Windows.Media.Imaging.BitmapFrameDecode.OnDownloadCompleted(Object sender, EventArgs e)
   at System.Windows.Media.UniqueEventHelper.InvokeEvents(Object sender, EventArgs args)
   at System.Windows.Media.Imaging.LateBoundBitmapDecoder.DownloadCallback(Object arg)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
 
====================================
END EXCEPTION REPORT
====================================
```

Notes:

User indicated they reproduced by being spammed with a wall of eicons. Combined with the user's reports of high memory use and the research I done on this, this could be a memory leak with eicons.

**Comment by nirschw** [comment]
I've the exact same problem
