### ISSUE TITLE
"The given key was not present in the dictionary."

### ISSUE THREAD

**Issue by WreckedAvent** [WreckedAvent/slimCat#409]
Example:
```
Version: slimCat Cheetah 5.012 dev
Exception: The given key was not present in the dictionary.
Occured at: mscorlib

Immediate stack trace: TValue get_Item(TKey)   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at slimCat.Services.FlistService.HandleCommand(IDictionary`2 command)
   at Microsoft.Practices.Prism.Events.BackgroundEventSubscription`1.<>c__DisplayClass5.<InvokeAction>b__4(Object o)
   at System.Threading.QueueUserWorkItemCallback.WaitCallback_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()
```

**Comment by WreckedAvent** [comment]
Have more reports of this. Appears to be the most common crash so far.
