### ISSUE TITLE
slimCat crashed right after the server did. "(522) Origin Connection Time-out"

### ISSUE THREAD

**Issue by EnragedRabisu** [WreckedAvent/slimCat#410]
Crashlog:
```
====================================
BEGIN EXCEPTION REPORT
9/2/2016 8:23:01 PM
====================================

Version: slimCat Cheetah 5.012 dev
Exception: The remote server returned an error: (522) Origin Connection Time-out.
Occured at: System

Immediate stack trace: System.Net.WebResponse GetResponse()   at System.Net.HttpWebRequest.GetResponse()
   at slimCat.Services.BrowserService.GetResponse(String host, IDictionary`2 arguments, Boolean useCookies)
   at slimCat.Services.TicketService.GetNewTicket()
   at slimCat.Services.TicketService.get_Ticket()
   at slimCat.Services.FchatService.ConnectionOpened(Object sender, EventArgs e)
   at WebSocket4Net.WebSocket.OnHandshaked()
   at WebSocket4Net.Command.Handshake.ExecuteCommand(WebSocket session, WebSocketCommandInfo commandInfo)
   at WebSocket4Net.WebSocket.ExecuteCommand(WebSocketCommandInfo commandInfo)
   at WebSocket4Net.WebSocket.OnDataReceived(Byte[] data, Int32 offset, Int32 length)
   at WebSocket4Net.WebSocket.client_DataReceived(Object sender, DataEventArgs e)
   at SuperSocket.ClientEngine.ClientSession.OnDataReceived(Byte[] data, Int32 offset, Int32 length)
   at SuperSocket.ClientEngine.SslStreamTcpSession.OnDataRead(IAsyncResult result)
   at System.Net.LazyAsyncResult.Complete(IntPtr userToken)
   at System.Net.LazyAsyncResult.ProtectedInvokeCallback(Object result, IntPtr userToken)
   at System.Net.Security._SslStream.ProcessFrameBody(Int32 readBytes, Byte[] buffer, Int32 offset, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security._SslStream.ReadFrameCallback(AsyncProtocolRequest asyncRequest)
   at System.Net.AsyncProtocolRequest.CompleteRequest(Int32 result)
   at System.Net.FixedSizeReader.CheckCompletionBeforeNextRead(Int32 bytes)
   at System.Net.FixedSizeReader.ReadCallback(IAsyncResult transportResult)
   at System.Net.LazyAsyncResult.Complete(IntPtr userToken)
   at System.Net.ContextAwareResult.CompleteCallback(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Net.ContextAwareResult.Complete(IntPtr userToken)
   at System.Net.LazyAsyncResult.ProtectedInvokeCallback(Object result, IntPtr userToken)
   at System.Net.Sockets.BaseOverlappedAsyncResult.CompletionPortCallback(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* nativeOverlapped)
   at System.Threading._IOCompletionCallback.PerformIOCompletionCallback(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* pOVERLAP)

====================================
END EXCEPTION REPORT
====================================
```

**Comment by WreckedAvent** [comment]
Well .... 

This'll be fun to test, I guess.
