### ISSUE TITLE
5.013 Crash On Bad Server Ticket Response

### ISSUE THREAD

**Issue by eradis** [WreckedAvent/slimCat#416]
They rebooted chat (and presumably more) and slimCat crashed trying to get a new ticket.

```
Version: slimCat Cheetah 5.013 dev
Exception: The remote server returned an error: (502) Bad Gateway.
Occured at: System

Immediate stack trace: System.Net.WebResponse GetResponse()   at System.Net.HttpWebRequest.GetResponse()
   at slimCat.Services.BrowserService.GetResponse(String host, IDictionary`2 arguments, Boolean useCookies)
   at slimCat.Services.TicketService.GetNewTicket()
   at slimCat.Services.TicketService.get_Ticket()
   at slimCat.Services.FchatService.ConnectionOpened(Object sender, EventArgs e)
   at WebSocket4Net.WebSocket.OnHandshaked()
   at WebSocket4Net.Command.Handshake.ExecuteCommand(WebSocket session, WebSocketCommandInfo commandInfo)
   at WebSocket4Net.WebSocket.ExecuteCommand(WebSocketCommandInfo commandInfo)
   at WebSocket4Net.WebSocket.OnDataReceived(Byte[] data, Int32 offset, Int32 length)
   at WebSocket4Net.WebSocket.client_DataReceived(Object sender, DataEventArgs e)
   at SuperSocket.ClientEngine.ClientSession.OnDataReceived(Byte[] data, Int32 offset, Int32 length)
   at SuperSocket.ClientEngine.SslStreamTcpSession.OnDataRead(IAsyncResult result)
   at System.Net.LazyAsyncResult.Complete(IntPtr userToken)
   at System.Net.LazyAsyncResult.ProtectedInvokeCallback(Object result, IntPtr userToken)
   at System.Net.Security._SslStream.ProcessFrameBody(Int32 readBytes, Byte[] buffer, Int32 offset, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security._SslStream.ReadFrameCallback(AsyncProtocolRequest asyncRequest)
   at System.Net.AsyncProtocolRequest.CompleteRequest(Int32 result)
   at System.Net.FixedSizeReader.CheckCompletionBeforeNextRead(Int32 bytes)
   at System.Net.FixedSizeReader.ReadCallback(IAsyncResult transportResult)
   at System.Net.LazyAsyncResult.Complete(IntPtr userToken)
   at System.Net.ContextAwareResult.CompleteCallback(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Net.ContextAwareResult.Complete(IntPtr userToken)
   at System.Net.LazyAsyncResult.ProtectedInvokeCallback(Object result, IntPtr userToken)
   at System.Net.Sockets.BaseOverlappedAsyncResult.CompletionPortCallback(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* nativeOverlapped)
   at System.Threading._IOCompletionCallback.PerformIOCompletionCallback(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* pOVERLAP)
```

**Comment by eradis** [comment]
Possibly a duplicate of #410

**Comment by WreckedAvent** [comment]
this is a generic error that happens when it can't reach f-list for whatever reason. I suppose it being down would qualify as "whatever reason".
